// raw_aliases.js
export const rawAliases = {
    "ATM": "financial",
    "Airport": "airport",
    "Airport Gate": "airport_gate",
    "Airport Terminal": "airport",
    "Airport Tram Station": "airport_tram",
    "American Restaurant": "newamerican",
    "Amphitheater": "arts_entertainment_default",
    "Amusement Park": "themepark",
    "Antique Store": "antique",
    "Apartment or Condo": "apartment",
    "Arcade": "arcade",
    "Art Gallery": "artgallery",
    "Art Museum": "museum_art",
    "Arts and Crafts Store": "artstore",
    "Arts and Entertainment": "arts_entertainment_default",
    "Asian Restaurant": "asian",
    "Attraction": "themepark",
    "Australian Restaurant": "australian",
    "BBQ Joint": "bbq",
    "Bagel Shop": "bagels",
    "Bakery": "bakery",
    "Bar": "bar",
    "Barbershop": "salon_barber",
    "Baseball Field": "baseballfield",
    "Baseball Stadium": "baseballfield",
    "Basketball Stadium": "stadium_basketball",
    "Beach": "beach",
    "Beach Bar": "nightlife_default",
    "Beer Bar": "pub",
    "Beer Garden": "beergarden",
    "Beer Store": "beergarden",
    "Bicycle Store": "bikeshop",
    "Big Box Store": "shops_default",
    "Bike Trail": "hikingtrail",
    "Bistro": "food_default",
    "Board Store": "surfspot",
    "Boat or Ferry": "ferry_pier",
    "Bookstore": "bookstore",
    "Botanical Garden": "botanicalgarden",
    "Boutique": "apparel_boutique",
    "Bowling Alley": "bowling",
    "Bratwurst Joint": "german",
    "Brazilian Restaurant": "argentinian",
    "Breakfast Spot": "breakfast",
    "Brewery": "brewery",
    "Bridge": "bridge",
    "Bubble Tea Shop": "tearoom",
    "Burger Joint": "burger",
    "Burrito Restaurant": "burrito",
    "Business Service": "building_default",
    "Café": "cafe",
    "Campground": "campground",
    "Candy Store": "candystore",
    "Caribbean Restaurant": "caribbean",
    "Carpet Store": "building/default",
    "Cheese Store": "cheese",
    "Chinese Restaurant": "asian",
    "Chocolate Store": "candy",
    "Christmas Market": "shops_default",
    "Church": "religious_church",
    "City": "",
    "City Hall": "cityhall",
    "Climbing Gym": "gym",
    "Clothing Store": "apparel",
    "Club House": "building_default",
    "Cocktail Bar": "cocktails",
    "Coffee Shop": "coffeeshop",
    "College Technology Building": "education_default",
    "Comedy Club": "comedyclub",
    "Comfort Food Restaurant": "food_default",
    "Conference Room": "conventioncenter_meetingroom",
    "Construction Supplies Store": "realestate",
    "Convenience Store": "conveniencestore",
    "Convention Center": "conventioncenter",
    "Corporate Cafeteria": "cafeteria",
    "Cosmetics Store": "beauty_cosmetic",
    "Costume Store": "shops_default",
    "Coworking Space": "office_coworkingspace",
    "Cuban Restaurant": "cuban",
    "Dance Studio": "performingarts_dancestudio",
    "Deli": "deli",
    "Dentist": "medical_dentist",
    "Department Store": "departmentstore",
    "Design Studio": "design",
    "Dessert Shop": "dessert",
    "Dim Sum Restaurant": "dimsum",
    "Diner": "diner",
    "Distillery": "brewery",
    "Dive Bar": "divebar",
    "Dog Park": "dogrun",
    "Donut Shop": "donuts",
    "Drugstore": "pharmacy",
    "Dutch Restaurant": "food_default",
    "Duty-free Store": "shops_default",
    "Eastern European Restaurant": "food_default",
    "Electronics Store": "technology",
    "Elementary School": "building_school",
    "Emergency Room": "medical",
    "English Restaurant": "food_default",
    "Event Space": "events_default",
    "Eyecare Store": "medical_opticalshop",
    "Factory": "factory",
    "Falafel Restaurant": "falafel",
    "Farmers Market": "food_farmersmarket",
    "Fashion Accessories Store": "apparel_accessories",
    "Fast Food Restaurant": "fastfood",
    "Festival": "event_default",
    "Field": "field",
    "Fish and Chips Shop": "fishandchips",
    "Flea Market": "fleamarket",
    "Flower Store": "flowershop",
    "Food Court": "food_foodcourt",
    "Food Truck": "streetfood",
    "Food and Beverage Retail": "foodanddrink",
    "Framing Store": "artgallery",
    "French Restaurant": "french",
    "Fried Chicken Joint": "friedchicken",
    "Frozen Yogurt Shop": "frozenyogurt",
    "Furniture and Home Store": "furniture",
    "Garden": "garden",
    "Garden Center": "gardencenter",
    "Gastropub": "gastropub",
    "German Restaurant": "german",
    "Gift Store": "giftshop",
    "Gluten-Free Restaurant": "gluetenfree",
    "Gourmet Store": "food_gourmet",
    "Government Building": "government",
    "Greek Restaurant": "greek",
    "Grocery Store": "food_grocery",
    "Gym": "gym",
    "Gym and Studio": "gym",
    "Hair Salon": "salon_barber",
    "Harbor or Marina": "harbor",
    "Hardware Store": "hardware",
    "Hawaiian Restaurant": "food_default",
    "Health Food Store": "food_grocery",
    "High School": "school",
    "Hiking Trail": "hikingtrail",
    "Hill": "parks_outdoors_default",
    "Historic and Protected Site": "historicsite",
    "History Museum": "museum_history",
    "Hockey Stadium": "stadium_hockey",
    "Hospital": "medical",
    "Hot Dog Joint": "hotdog",
    "Hotel": "hotel",
    "Hotel Bar": "hotel_bar",
    "Hotel Pool": "pool",
    "Hotpot Restaurant": "vietnamese",
    "IT Service": "technology",
    "Ice Cream Parlor": "icecream",
    "Indian Restaurant": "indian",
    "International Airport": "airport",
    "Irish Pub": "pub",
    "Island": "",
    "Israeli Restaurant": "falafel",
    "Italian Restaurant": "italian",
    "Japanese Curry Restaurant": "japanese",
    "Japanese Restaurant": "japanese",
    "Jewelry Store": "jewelry",
    "Jewish Restaurant": "food_default",
    "Jiangsu Restaurant": "asian",
    "Juice Bar": "juiebar",
    "Karaoke Bar": "karaoke",
    "Kitchen Supply Store": "food_butcher",
    "Korean Restaurant": "korean",
    "Laundry Service": "laundry",
    "Leather Goods Store": "shops_default",
    "Legal Service": "lawschool",
    "Library": "library",
    "Liquor Store": "food_liquor",
    "Lounge": "nightlife_default",
    "Marine Terminal": "boat",
    "Market": "market",
    "Martial Arts Dojo": "korean",
    "Medical Center": "medical",
    "Mediterranean Restaurant": "mediterranean",
    "Memorial Site": "historicsite",
    "Men's Store": "apparel_men",
    "Metro Station": "subway",
    "Mexican Restaurant": "mexican",
    "Middle Eastern Restaurant": "middleeastern",
    "Mini Golf Course": "golfcourse",
    "Miscellaneous Store": "shops_default",
    "Mobile Phone Store": "mobilephoneshop",
    "Monument": "government_monument",
    "Moroccan Restaurant": "moroccan",
    "Movie Theater": "movietheater",
    "Moving Target": "movingtarget",
    "Museum": "museum",
    "Music Festival": "musicvenue_rockclub",
    "Music Store": "shops_default",
    "Music Venue": "musicvenue",
    "National Park": "hikingtrail",
    "Neighborhood": "",
    "New American Restaurant": "newamerican",
    "Night Club": "nightclub",
    "Noodle Restaurant": "ramen",
    "North Indian Restaurant": "indian",
    "Office": "building_default",
    "Organic Grocery": "food_grocery",
    "Other Great Outdoors": "outdoors",
    "Outdoor Supply Store": "shops_default",
    "Park": "parks_outdoors_default",
    "Pedestrian Plaza": "parks_outdoors_default",
    "Performing Arts Venue": "performingarts",
    "Pet Service": "pet_store",
    "Pharmacy": "pharmacy",
    "Photography Lab": "photographylab",
    "Pie Shop": "pieshop",
    "Pier": "ferry_pier",
    "Pizzeria": "pizza",
    "Plane": "airport",
    "Planetarium": "museum_planetarium",
    "Platform": "trainstation",
    "Playground": "playground",
    "Plaza": "parks_outdoors_default",
    "Police Station": "government_policestation",
    "Pool Hall": "billiards",
    "Pop-Up Store": "shops_default",
    "Post Office": "postoffice",
    "Print Store": "shops_default",
    "Prison": "building_default",
    "Pub": "pub",
    "Public Art": "events_default",
    "Radio Station": "building_default",
    "Rail Station": "trainstation",
    "Ramen Restaurant": "ramen",
    "Record Store": "record_shop",
    "Rental Car Location": "airport_rentalcar",
    "Repair Service": "shops_default",
    "Rest Area": "restarea",
    "Restaurant": "restaurant",
    "Road": "highway",
    "Rock Club": "musicvenue_rockclub",
    "Roof Deck": "hotel_roofdeck",
    "Sake Bar": "sake",
    "Salad Restaurant": "salad",
    "Sandwich Spot": "deli",
    "Scenic Lookout": "sceniclookout",
    "Sculpture Garden": "sculpture",
    "Seafood Restaurant": "seafood",
    "Shanghai Restaurant": "asian",
    "Shoe Store": "apparel_shoestore",
    "Shopping Mall": "mall",
    "Skate Store": "skate_park",
    "Skating Rink": "skatingrink",
    "Soccer Field": "stadium_soccer",
    "Soccer Stadium": "stadium_soccer",
    "Social Club":  "building_default",
    "Soup Spot": "soup",
    "Southern Food Restaurant": "southern",
    "Spa": "spa",
    "Spanish Restaurant": "spanish",
    "Speakeasy": "secretbar",
    "Sporting Goods Retail": "sports_outdoors",
    "Sports Bar": "sportsbar",
    "Sports and Recreation": "sports_outdoors",
    "State or Provincial Park": "parks_outdoors_default",
    "Stationery Store": "shops_default",
    "Steakhouse": "steakhouse",
    "Street Art": "arts_entertainment_default",
    "Street Food Gathering": "streetfood",
    "Structure": "building_default",
    "Supermarket": "grocery",
    "Sushi Restaurant": "sushi",
    "Taco Restaurant": "taco",
    "Tapas Restaurant": "tapas",
    "Tea Room": "tearoom",
    "Tech Startup": "technology",
    "Tennis Club": "stadium_tennis",
    "Tennis Stadium": "stadium_tennis",
    "Thai Restaurant": "thai",
    "Theater": "performingarts",
    "Theme Restaurant": "food_default",
    "Tiki Bar": "cocktails",
    "Tourist Information and Service": "touristinformation",
    "Town": "",
    "Toy Store": "toys",
    "Track": "stadium_track",
    "University": "education_default",
    "Urgent Care Center": "medical",
    "Used Bookstore": "bookstore",
    "Vegan and Vegetarian Restaurant": "vegetarian",
    "Video Games Store": "videogames",
    "Vietnamese Restaurant": "vietnamese",
    "Vintage and Thrift Store": "shops_default",
    "Whisky Bar": "whiskey",
    "Wine Bar": "winery",
    "Wine Store": "food_wineshop",
    "Women's Store": "apparel_women",
    "default": "none_default"
};