const tickets = [
  {
    stub: "/_/images/tickets/gigs/2002/03/20-travis.jpg",
    band: "Travis",
    venue: "SECC",
    district: "Glasgow",
    date: "20th March",
    year: "2002",
    story:
      "The first concert I was allowed to go to by myself, Doves were the support act.",
  },
  {
    stub: "/_/images/tickets/gigs/2003/03/05-red-hot-chili-peppers.jpg",
    band: "Red Hot Chili Peppers",
    venue: "SECC",
    district: "Glasgow",
    date: "5th March",
    year: "2003",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2004/01/25-the-white-stripes.jpg",
    band: "The White Stripes",
    venue: "SECC",
    district: "Glasgow",
    date: "25th January",
    year: "2004",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2004/06/10-jet.jpg",
    band: "Jet",
    venue: "Carling Academy",
    district: "Glasgow",
    date: "10th June",
    year: "2004",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2004/10/07-razorlight.jpg",
    band: "Razorlight",
    venue: "Barrowlands",
    district: "Glasgow",
    date: "7th October",
    year: "2004",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2004/10/16-franz-ferdinand.jpg",
    band: "Franz Ferdinand",
    venue: "Barrowlands",
    district: "Glasgow",
    date: "16th October",
    year: "2004",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2005/01/21-nme-tour.jpg",
    band: "NME Tour",
    venue: "Carling Academy",
    district: "Glasgow",
    date: "21st January",
    year: "2005",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2005/02/06-razorlight.jpg",
    band: "Razorlight",
    venue: "Carling Academy",
    district: "Glasgow",
    date: "6th February",
    year: "2005",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2005/04/15-bloc-party.jpg",
    band: "Bloc Party",
    venue: "Barrowlands",
    district: "Glasgow",
    date: "15th April",
    year: "2005",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2005/04/17-the-music.jpg",
    band: "The Music",
    venue: "Greenock Town Hall",
    district: "Greenock",
    date: "17th April",
    year: "2005",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2005/06/02-hudson.jpg",
    band: "Hudson",
    venue: "Lava Lounge",
    district: "Greenock",
    date: "2nd June",
    year: "2005",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2005/11/13-paul-weller.jpg",
    band: "Paul Weller",
    venue: "SECC",
    district: "Glasgow",
    date: "13th November",
    year: "2005",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2005/11/19-british-sea-power.jpg",
    band: "British Sea Power",
    venue: "QMU",
    district: "Glasgow",
    date: "19th November",
    year: "2005",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2005/12/05-maximo-park.jpg",
    band: "Maximo Park",
    venue: "Barrowlands",
    district: "Glasgow",
    date: "5th December",
    year: "2005",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2006/02/06-all-american-rejects.jpg",
    band: "All American Rejects",
    venue: "QMU",
    district: "Glasgow",
    date: "6th February",
    year: "2006",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2006/02/08-the-strokes.jpg",
    band: "The Strokes",
    venue: "Carling Academy",
    district: "Glasgow",
    date: "8th February",
    year: "2006",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2006/02/10-ian-brown.jpg",
    band: "Ian Brown",
    venue: "Braehead Arena",
    district: "Glasgow",
    date: "10th February",
    year: "2006",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2006/02/23-delays.jpg",
    band: "Delays",
    venue: "QMU",
    district: "Glasgow",
    date: "23rd February",
    year: "2006",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2006/04/08-we-are-scientists.jpg",
    band: "We Are Scientists",
    venue: "QMU",
    district: "Glasgow",
    date: "8th April",
    year: "2006",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2006/05/13-radio-ones-big-weekend.jpg",
    band: "Radio 1's Big Weekend",
    venue: "Camperdown Park",
    district: "Dundee",
    date: "13th May",
    year: "2006",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2006/05/29-the-futureheads.jpg",
    band: "The Futureheads",
    venue: "Carling Academy",
    district: "Glasgow",
    date: "29th May",
    year: "2006",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2006/07/08-t-in-the-park.jpg",
    band: "T in the Park",
    venue: "Balado",
    district: "Kinross",
    date: "8th-9th July",
    year: "2006",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2006/09/08-british-sea-power.jpg",
    band: "British Sea Power",
    venue: "King Tuts Wah Wah Hut",
    district: "Glasgow",
    date: "8th September",
    year: "2006",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2006/10/13-milburn.jpg",
    band: "Milburn",
    venue: "QMU",
    district: "Glasgow",
    date: "13th October",
    year: "2006",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2006/10/25-the-rifles.jpg",
    band: "The Rifles",
    venue: "King Tuts Wah Wah Hut",
    district: "Glasgow",
    date: "25th October",
    year: "2006",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2006/11/03-jet.jpg",
    band: "Jet",
    venue: "Barrowlands",
    district: "Glasgow",
    date: "3rd November",
    year: "2006",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2006/11/21-the-feeling.jpg",
    band: "The Feeling",
    venue: "ABC",
    district: "Glasgow",
    date: "21st November",
    year: "2006",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2007/02/17-bloc-party.jpg",
    band: "Bloc Party",
    venue: "Barrowlands",
    district: "Glasgow",
    date: "17th February",
    year: "2007",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2007/02/22-the-killers.jpg",
    band: "The Killers",
    venue: "SECC",
    district: "Glasgow",
    date: "22nd February",
    year: "2007",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2007/03/01-little-man-tate.jpg",
    band: "Little Man Tate",
    venue: "QMU",
    district: "Glasgow",
    date: "1st March",
    year: "2007",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2007/05/03-the-sunshine-underground.jpg",
    band: "The Sunshine Underground",
    venue: "QMU",
    district: "Glasgow",
    date: "3rd May",
    year: "2007",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2007/07/06-t-in-the-park.jpg",
    band: "T in the Park",
    venue: "Balado",
    district: "Kinross",
    date: "6th-8th July",
    year: "2007",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2008/01/26-british-sea-power.jpg",
    band: "British Sea Power",
    venue: "The Arches",
    district: "Glasgow",
    date: "26th January",
    year: "2008",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2008/02/15-mark-ronson.jpg",
    band: "Mark Ronson",
    venue: "Carling Academy",
    district: "Glasgow",
    date: "15th February",
    year: "2008",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2008/02/28-young-knives.jpg",
    band: "Young Knives",
    venue: "The Classic Grand",
    district: "Glasgow",
    date: "28th February",
    year: "2008",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2008/05/22-milburn.jpg",
    band: "Milburn",
    venue: "ABC 2",
    district: "Glasgow",
    date: "22nd May",
    year: "2008",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2008/05/24-little-man-tate.jpg",
    band: "Little Man Tate",
    venue: "ABC 1",
    district: "Glasgow",
    date: "24th May",
    year: "2008",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2008/05/30-santogold.jpg",
    band: "Santogold",
    venue: "Sub Club",
    district: "Glasgow",
    date: "30th May",
    year: "2008",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2008/10/01-cajun-dance-party.jpg",
    band: "Cajun Dance Party",
    venue: "King Tuts Wah Wah Hut",
    district: "Glasgow",
    date: "1st October",
    year: "2008",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2009/03/23-james-morrison.jpg",
    band: "James Morrison",
    venue: "O2 Academy",
    district: "Glasgow",
    date: "23rd March",
    year: "2009",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2009/07/03-blur.jpg",
    band: "Blur",
    venue: "Hyde Park",
    district: "London",
    date: "3rd July",
    year: "2009",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2010/03/24-the-courteeners.jpg",
    band: "The Courteeners",
    venue: "O2 Academy",
    district: "Glasgow",
    date: "24th March",
    year: "2010",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2010/06/08-supergrass.jpg",
    band: "Supergrass",
    venue: "Barrowlands",
    district: "Glasgow",
    date: "8th June",
    year: "2010",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2010/09/17-two-door-cinema-club.jpg",
    band: "Two Door Cinema Club",
    venue: "Oran Mor",
    district: "Glasgow",
    date: "17th September",
    year: "2010",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2010/09/20-mgmt.jpg",
    band: "MGMT",
    venue: "Barrowlands",
    district: "Glasgow",
    date: "20th September",
    year: "2010",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2010/10/02-yeasayer.jpg",
    band: "Yeasayer",
    venue: "O2 ABC",
    district: "Glasgow",
    date: "24th October",
    year: "2010",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2010/10/30-mystery-jets.jpg",
    band: "Mystery Jets",
    venue: "O2 ABC",
    district: "Glasgow",
    date: "30th October",
    year: "2010",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2010/11/01-marina-and-the-diamonds.jpg",
    band: "Marina and the Diamonds",
    venue: "Old Fruitmarket",
    district: "Glasgow",
    date: "1st November",
    year: "2010",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2010/12/05-the-courteeners.jpg",
    band: "The Courteeners",
    venue: "Barrowlands",
    district: "Glasgow",
    date: "5th December",
    year: "2010",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2010/12/12-arcade-fire.jpg",
    band: "Arcade Fire",
    venue: "SECC",
    district: "Glasgow",
    date: "12th December",
    year: "2010",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2010/12/29-the-complete-stone-roses.jpg",
    band: "The Complete Stone Roses",
    venue: "Word Up",
    district: "Greenock",
    date: "29th December",
    year: "2010",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2011/02/04-hurts.jpg",
    band: "Hurts",
    venue: "O2 ABC",
    district: "Glasgow",
    date: "4th February",
    year: "2011",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2011/02/10-chapel-club.jpg",
    band: "Chapel Club",
    venue: "King Tuts Wah Wah Hut",
    district: "Glasgow",
    date: "10th February",
    year: "2011",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2011/03/05-surfer-blood.jpg",
    band: "Surfer Blood",
    venue: "King Tuts Wah Wah Hut",
    district: "Glasgow",
    date: "5th March",
    year: "2011",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2011/03/10-two-door-cinema-club.jpg",
    band: "Two Door Cinema Club",
    venue: "O2 ABC",
    district: "Glasgow",
    date: "10th March",
    year: "2011",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2011/03/11-mona.jpg",
    band: "Mona",
    venue: "King Tuts Wah Wah Hut",
    district: "Glasgow",
    date: "11th March",
    year: "2011",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2011/04/05-the-vaccines.jpg",
    band: "The Vaccines",
    venue: "O2 ABC",
    district: "Glasgow",
    date: "5th April",
    year: "2011",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2011/04/27-best-coast.jpg",
    band: "Best Coast",
    venue: "The Arches",
    district: "Glasgow",
    date: "27th April",
    year: "2011",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2011/08/24-the-national.jpg",
    band: "The National",
    venue: "O2 Academy",
    district: "Glasgow",
    date: "24th August",
    year: "2011",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2011/10/07-the-wombats.jpg",
    band: "The Wombats",
    venue: "O2 Academy",
    district: "Glasgow",
    date: "7th October",
    year: "2011",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2011/10/19-miles-kane.jpg",
    band: "Miles Kane",
    venue: "O2 Academy",
    district: "Glasgow",
    date: "19th October",
    year: "2011",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2011/10/26-the-maccabees.jpg",
    band: "The Maccabees",
    venue: "The Arches",
    district: "Glasgow",
    date: "19th October",
    year: "2011",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2011/11/12-red-hot-chili-peppers.jpg",
    band: "Red Hot Chili Peppers",
    venue: "SECC",
    district: "Glasgow",
    date: "12th November",
    year: "2011",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2011/11/19-the-vaccines.jpg",
    band: "The Vaccines",
    venue: "Barrowlands",
    district: "Glasgow",
    date: "19th November",
    year: "2011",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2011/12/02-shed-seven.jpg",
    band: "Shed Seven",
    venue: "Barrowlands",
    district: "Glasgow",
    date: "2nd December",
    year: "2011",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2011/12/15-white-lies.jpg",
    band: "White Lies",
    venue: "O2 Academy",
    district: "Glasgow",
    date: "15th December",
    year: "2011",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2012/03/03-the-cribs.jpg",
    band: "The Cribs",
    venue: "The Stage",
    district: "Leeds",
    date: "3rd March",
    year: "2012",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2012/04/11-frightened-rabbit.jpg",
    band: "Frightened Rabbit",
    venue: "Cafe Continental",
    district: "Gourock",
    date: "11th April",
    year: "2012",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2012/04/22-admiral-fallow.jpg",
    band: "Admiral Fallow",
    venue: "Cafe Continental",
    district: "Gourock",
    date: "22nd April",
    year: "2012",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2012/05/11-the-cribs.jpg",
    band: "The Cribs",
    venue: "Barrowlands",
    district: "Glasgow",
    date: "11th May",
    year: "2012",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2012/06/16-best-coast.jpg",
    band: "Best Coast",
    venue: "O2 ABC",
    district: "Glasgow",
    date: "16th June",
    year: "2012",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2012/06/29-the-stone-roses.jpg",
    band: "The Stone Roses",
    venue: "Heaton Park",
    district: "Manchester",
    date: "29th June",
    year: "2012",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2012/12/08-admiral-fallow.jpg",
    band: "Admiral Fallow",
    venue: "Barrowlands",
    district: "Glasgow",
    date: "8th December",
    year: "2012",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2013/04/",
    band: "Frightened Rabbit",
    venue: "Terminal 5",
    district: "Manhattan",
    date: "4th April",
    year: "2013",
    story: "",
    hidden: true,
  },
  {
    stub: "/_/images/tickets/gigs/2013/06/15-the-stone-roses.jpg",
    band: "The Stone Roses",
    venue: "Glasgow Green",
    district: "Glasgow",
    date: "15th June",
    year: "2013",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2013/10/07-paul-weller.jpg",
    band: "Paul Weller",
    venue: "Barrowlands",
    district: "Glasgow",
    date: "7th October",
    year: "2013",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2013/11/21-arctic-monkeys.jpg",
    band: "Arctic Monkeys",
    venue: "SSE Hydro",
    district: "Glasgow",
    date: "21st November",
    year: "2013",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2014/01/31-tommy-reilly.jpg",
    band: "Tommy Reilly",
    venue: "Cafe Continental",
    district: "Gourock",
    date: "31st January",
    district: "2014",
    story: "",
    hidden: true,
  },
  {
    stub: "/_/images/tickets/gigs/2014/05/09-bombay-bicycle-club.jpg",
    band: "Bombay Bicycle Club",
    venue: "Webster Hall",
    district: "Manhattan",
    date: "9th May",
    year: "2014",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2014/07/28-the-kooks.jpg",
    band: "The Kooks",
    venue: "Webster Hall",
    district: "Manhattan",
    date: "28th July",
    year: "2014",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2014/09/05-boston-calling.jpg",
    band: "Boston Calling",
    venue: "Boston City Hall Plaza",
    district: "Boston",
    date: "5th September",
    year: "2014",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2014/09/17-slow-club.jpg",
    band: "Slow Club",
    venue: "Bowery Ballroom",
    district: "Manhattan",
    date: "17th September",
    year: "2014",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2014/09/23-nada-surf.jpg",
    band: "Nada Surf",
    venue: "Rough Trade",
    district: "Brooklyn",
    date: "23rd September",
    year: "2014",
    story: "",
    hidden: true,
  },
  {
    stub: "/_/images/tickets/gigs/2014/10/14-owl-john.jpg",
    band: "Owl John",
    venue: "The Bell House",
    district: "Manhattan",
    date: "14th October",
    year: "2014",
    story: "",
    hidden: true,
  },
  {
    stub: "/_/images/tickets/gigs/2014/10/16-the-twilight-sad.jpg",
    band: "The Twilight Sad",
    venue: "Rough Trade",
    district: "Brooklyn",
    date: "16th October",
    year: "2014",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2014/11/23-we-were-promised-jetpacks.jpg",
    band: "We Were Promised Jetpacks",
    venue: "Webster Hall",
    district: "Manhattan",
    date: "23rd November",
    year: "2014",
    story: "",
    hidden: true,
  },
  {
    stub: "/_/images/tickets/gigs/2015/08/02-clap-your-hands-say-yeah.jpg",
    band: "Clap Your Hands Say Yeah",
    venue: "Bowery Ballroom",
    district: "Manhattan",
    date: "2nd August",
    year: "2015",
    story: "",
    hidden: true,
  },
  {
    stub: "/_/images/tickets/gigs/2015/09/01-the-vaccines.jpg",
    band: "The Vaccines",
    venue: "Rough Trade",
    district: "Brooklyn",
    date: "1st September",
    year: "2015",
    story: "",
    hidden: true,
  },
  {
    stub: "/_/images/tickets/gigs/2015/11/10-surfer-blood.jpg",
    band: "Surfer Blood",
    venue: "Rough Trade",
    district: "Brooklyn",
    date: "10th November",
    year: "2015",
    story: "",
    hidden: true,
  },
  {
    stub: "/_/images/tickets/gigs/2016/01/21-the-libertines.jpg",
    band: "The Libertines",
    venue: "SSE Hydro",
    district: "Glasgow",
    date: "21st January",
    year: "2016",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2016/05/31-we-were-promised-jetpacks.jpg",
    band: "We Were Promised Jetpacks",
    venue: "Bowery Ballroom",
    district: "Manhattan",
    date: "31st May",
    year: "2016",
    story: "",
    hidden: true,
  },
  {
    stub: "/_/images/tickets/gigs/2015/09/05-stereophonics.jpg",
    band: "Stereophonics",
    venue: "Irvine Plaza",
    district: "Manhattan",
    date: "5th September",
    year: "2017",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2016/09/29-the-national.jpg",
    band: "The National",
    venue: "Forest Hills Stadium",
    district: "Queens",
    date: "29th September",
    year: "2018",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2017/10/20-the-dan-band.jpg",
    band: "The Dan Band",
    venue: "Highline Ballroom",
    district: "Manhattan",
    date: "20th October",
    year: "2017",
    story: "",
    hidden: true,
  },
  {
    stub: "/_/images/tickets/gigs/2017/11/27-liam-gallagher.jpg",
    band: "Liam Gallagher",
    venue: "Terminal 5",
    district: "Manhattan",
    date: "27th November",
    year: "2017",
    story: "",
    hidden: true,
  },
  {
    stub: "/_/images/tickets/gigs/2019/12/21-gerry-cinnamon.jpg",
    band: "Gerry Cinnamon",
    venue: "SSE Hydro",
    district: "Glasgow",
    date: "12th January",
    year: "2019",
    story: "",
  },
  {
    stub: "/_/images/tickets/gigs/2020/01/27-the-teskey-brothers.jpg",
    band: "The Teskey Brothers",
    venue: "Saint Luke's",
    district: "Glasgow",
    date: "27th January",
    year: "2020",
    story: "",
  },
];

module.exports = () => {
  return tickets.filter((ticket) => !ticket.hidden);
};
